### Registrar usuario
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "email": "juan@example2.com",
  "password": "123456"
}

###

### Login
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "email": "juan@example2.com",
  "password": "123456"
}

###

### Obtener perfil (profile)
GET http://localhost:8000/api/auth/profile
# Asegúrate de enviar cookies habilitadas

###

### Logout
POST http://localhost:8000/api/auth/logout
# Cookie 'token' se eliminará
